
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - service.consul.k8s.nativechat.com
  resources:
  - consulserviceroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service.consul.k8s.nativechat.com
  resources:
  - consulserviceroutes/finalizers
  verbs:
  - update
- apiGroups:
  - service.consul.k8s.nativechat.com
  resources:
  - consulserviceroutes/status
  verbs:
  - get
  - patch
  - update
