apiVersion: service.consul.k8s.nativechat.com/v1alpha1
kind: ConsulServiceRoute
metadata:
  name: consulserviceroute-sample
  labels:
    service.consul.k8s.nativechat.com/service-router: consulserviceroute
spec:
  route:
    match:
      http:
        pathPrefix: /v1
    destination:
      service: consulserviceroute-sample
